name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"
  LABEL: "test"

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    # runs-on: ["self-hosted", "test-on-aks"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LABEL: [ "engine" ]
    environment: test-on-aks

    # needs: [buildImage]
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |-
          echo "This is a message for the custom runner"
          echo "LABELS are ${{ matrix.LABEL }}"
        
      - name: Step
        if: ${{ matrix.LABEL == 'test' }}
        env:
          SHA: ${GITHUB_SHA:0:7}
          SECTET: ${{secrets.TEST_PASSWORD}}
        run: |-
          echo ${GITHUB_SHA:0:7}
          echo $SHA
          touch dev.env
          echo TEST_PASSOWRD=$SECTET >> dev.env
          echo $TEST_PASSOWRD
          cat dev.env
          echo ${{ matrix.LABEL }}
      - name: testing-deploy
        uses: ${{github.workspace}}/.github/action.yaml
        with:
          LABEL: ${{matrix.LABEL}}

