name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"
  LABEL: "test"

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    # runs-on: ["self-hosted", "test-on-aks"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LABEL: ["${{ env.LABEL }}"]
    environment: test-on-aks
    if: ${{matrix.LABEL}} == 'test'
    # needs: [buildImage]
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: echo "This is a message for the custom runner"
        
      - name: Step
        env:
          SHA: ${GITHUB_SHA:0:7}
          SECTET: ${{secrets.TEST_PASSWORD}}
        run: |-
          echo ${GITHUB_SHA:0:7}
          echo $SHA
          touch dev.env
          echo TEST_PASSOWRD=$SECTET >> dev.env
          echo $TEST_PASSOWRD
          cat dev.env
          echo ${{matrix.LABEL}}
      # # Use kubelogin to configure your kubeconfig for Azure auth
      # - name: Set up kubelogin for non-interactive login
      #   uses: azure/use-kubelogin@v1
      #   with:
      #     kubelogin-version: 'v0.0.25'

      # # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      # - name: Get K8s context
      #   uses: azure/aks-set-context@v3
      #   with:
      #     resource-group: ${{ env.RESOURCE_GROUP }}
      #     cluster-name: ${{ env.CLUSTER_NAME }}
      #     admin: 'false'
      #     use-kubelogin: 'true'

      # # Deploys application based on given manifest file
      # - name: Deploys application
      #   uses: Azure/k8s-deploy@v4
      #   with:
      #     action: deploy
      #     manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
      #     images: |
      #       ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
